/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/** This is the editor component that our filter will display.
*/
class WaveGenPluginAudioProcessorEditor  : public AudioProcessorEditor,
                                            private Timer,
                                            public SliderListener,
                                            public ComboBoxListener
{
    
public:
    WaveGenPluginAudioProcessorEditor (WaveGenPluginAudioProcessor& wavegen);
    ~WaveGenPluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void timerCallback() override;

private:
    class ParameterSlider;

    MidiKeyboardComponent midiKeyboard;
    Label timecodeDisplayLabel, gainLabel, delayLabel;
    ScopedPointer<ParameterSlider> gainSlider, delaySlider;

    ScopedPointer<Component> outputUI;
    ScopedPointer<ComboBox> waveType;
    
    ScopedPointer<Slider> tone, pwm, overtoneDepth, test;
    
    Label PWMLabel, toneLabel, depthLabel;
    
    void comboBoxChanged (ComboBox* comboBoxThatHasChanged) override;
    void sliderValueChanged(Slider* sliderThatWasMoved) override;
    
    //==============================================================================
    WaveGenPluginAudioProcessor& getProcessor() const
    {
        return static_cast<WaveGenPluginAudioProcessor&> (processor);
    }

    void updateTimecodeDisplay (AudioPlayHead::CurrentPositionInfo);
};

